apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: url-shortener
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: URL Shortener Platform Project
  sourceRepos:
    - "https://github.com/panche20/*"
  destinations:
    - namespace: url-shortener
      server: https://kubernetes.default.svc
    - namespace: url-shortener-dev
      server: https://kubernetes.default.svc
    - namespace: url-shortener-prod
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: Namespace
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: true