apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: url-shortener-dev
  namespace: argocd   # Applications always live here
  labels:
    environment: dev
    team: platform
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: url-shortener
  source:
    repoURL: https://github.com/panche20/day36-gitops
    targetRevision: HEAD
    path: helm/url-shortener
    helm:
      valueFiles:
      - values.yaml
      - values.dev.yaml
      parameters:
      - name: app.tag
        value: "v1.0.4"
  destination:
    server: https://kubernetes.default.svc
    namespace: url-shortener-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=false
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    # HPA can change replicas — don't fight with it
    - /spec/replicas
