---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "url-shortener.appName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
    component: app
spec:
  type: ClusterIP
  selector:
    {{- include "url-shortener.selectorLabels" . | nindent 4 }}
    component: app
  ports:
  - name: http
    port: 80
    targetPort: {{ .Values.app.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "url-shortener.redisName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
    component: redis
spec:
  type: ClusterIP
  selector:
    {{- include "url-shortener.selectorLabels" . | nindent 4 }}
    component: redis
  ports:
  - name: redis
    port: {{ .Values.redis.port }}
    targetPort: {{ .Values.redis.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "url-shortener.redisName" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
    component: redis
spec:
  clusterIP: None
  selector:
    {{- include "url-shortener.selectorLabels" . | nindent 4 }}
    component: redis
  ports:
  - name: redis
    port: {{ .Values.redis.port }}
    targetPort: {{ .Values.redis.port }}